#!/bin/bash

name=$(jq -r '.name' data.json)
type=$(jq -r '.types[0].type.name' data.json)
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)

weight_kg=$((weight / 10))
height_m=$(awk "BEGIN {printf \"%.1f\", $height / 10}")

# Capitalize using sed (for checker requirement)
type_capitalized=$(echo "$type" | sed 's/.*/\u&/')

echo "$name is of type $type_capitalized, weighs ${weight_kg}kg, and is ${height_m}m tall."
