#!/bin/bash

name=$(jq -r '.name' data.json)
type=$(jq -r '.types[0].type.name' data.json)
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)

# Format values
formatted_weight=$((weight / 10))
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height / 10}")

# Capitalize name and type using sed
name_capitalized=$(echo "$name" | sed 's/.*/\u&/')
type_capitalized=$(echo "$type" | sed 's/.*/\u&/')

# Final output
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
